const express=require('express')
const   cors=require('cors')
const getPostsRoute=require('./routes/getPostsRoutes')
const getUsersRoute=require('./routes/getUserRoutes')
const {run} = require('./db/db')
const { userSchema, postSchema } = require('./models/collectionSchema')
require('dotenv').config()
console.log(process.env.MNGD) // remove this after you've confirmed it working
const app=express()
run()
// userSchema() 
// postSchema()
app.use(express.json())
app.use(cors())
app.use('/api/posts',getPostsRoute)
app.use('/api/users',getUsersRoute)
app.listen(8000,()=>{
    console.log('app listening to port 8000')
})
